name: ui_design
description: "A new Flutter project."

# Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  animated_read_more_text: ^0.0.6
  animations: ^2.0.11
  auto_size_text: ^3.0.0
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  drop_shadow: ^0.1.0
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_animated_button: ^2.0.3
  flutter_fadein: ^2.0.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_slidable: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  get_storage: ^2.1.1
  glass: ^2.0.0+1
  glossy: ^0.0.4
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  iconsax: ^0.0.8
  liquid_pull_to_refresh: ^3.0.1
  liquid_swipe: ^3.1.0
  local_auth: ^2.2.0
  nfc_manager: ^3.5.0
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  read_more_text: ^0.0.5
  readmore: ^3.0.0
  shadow: ^1.5.0
  simple_animations: ^5.0.2
  simple_shadow: ^0.3.1
  staggered_grid_view_flutter: ^0.0.4
  url_launcher: ^6.3.0
  uuid: ^4.2.2
  vertical_card_pager: ^1.5.0
  video_player: ^2.9.1
  flutter_load_kit: ^0.0.2
  flutter_verification_code: ^1.1.7
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/shoe_ui/1.png
    - assets/shoe_ui/2.png
    - assets/shoe_ui/3.png
    - assets/shoe_ui/4.png
    - assets/shoe_ui/5.png
    - assets/shoe_ui/6.png
    - assets/shoe_ui/7.png
    - assets/shoe_ui/8.jpg
    - assets/city_tour/thailand.jpg
    - assets/city_tour/bejing_china.jpg
    - assets/city_tour/new_york.jpg
    - assets/city_tour/singapore.jpg
    - assets/city_tour/tokyo_japan.jpg
    - assets/city_tour/syndey.jpg
    - assets/furniture/splash.jpg
    - assets/furniture/icons/right-down.png
    - assets/furniture/icons/arrow-long-left.svg
    - assets/furniture/icons/bag.svg
    - assets/furniture/icons/check.svg
    - assets/furniture/icons/home.svg
    - assets/furniture/icons/menu.svg
    - assets/furniture/icons/scan.svg
    - assets/furniture/icons/search.svg
    - assets/furniture/icons/user.svg
    - assets/furniture/icons/spinner.gif
    - assets/furniture/icons/ripple.gif
    - assets/travel_ui/payment.png
    - assets/travel_ui/relax.png
    - assets/travel_ui/images/safari.jpg
    - assets/travel_ui/images/victoria.jpg
    - assets/travel_ui/images/wall.jpg
    - assets/travel_ui/travel.png
    - assets/travel_ui/videos/safari.mp4
    - assets/travel_ui/videos/victoria.mp4
    - assets/travel_ui/videos/wall.mp4
    - assets/furniture_onboard/1.jpg
    - assets/furniture_onboard/2.jpg
    - assets/furniture_onboard/3.jpg
    - assets/otp/phone.png

    # gridview
    - assets/furniture_grid/1.jpg
    - assets/furniture_grid/2.jpg
    - assets/furniture_grid/3.jpg
    - assets/furniture_grid/4.jpg
    - assets/furniture_grid/5.jpg
    - assets/furniture_grid/6.jpg
    - assets/furniture_grid/7.jpg
    - assets/furniture_grid/8.jpg
    - assets/furniture_grid/9.jpg
    - assets/furniture_grid/animation/
    - assets/furniture_grid/categories/

    #form
    - assets/form/1.jpg
    - assets/form/2.jpg

    #social network
    - assets/social_net/1.png
    - assets/social_net/2.png
    - assets/social_net/3.png

    # watch
    - assets/smart/calendar.jpg
    - assets/smart/music.jpg
    - assets/smart/settings.jpg
    - assets/smart/alarm.jpg

    # coffee
    - assets/coffee_shop/
    - assets/coffee_shop/animation/
    - assets/coffee_shop/products/png/

    #minimal
    - assets/minimal_shop/
    - assets/minimal_shop/products/

    #dashboard
    - assets/dashboard/icons/
    - assets/dashboard/users/

    #grocery UI
    - assets/grocery/splash_main.jpg
    - assets/grocery/grocery_app_banner.jpg
    - assets/grocery/user.jpg
    - assets/grocery/logo.png
    - assets/grocery/products/
    - assets/grocery/products/veggie/
    - assets/grocery/category/

    #grocery2 UI
    - assets/grocery2/splash_main.jpg
    - assets/grocery2/products/

    #food menu
    - assets/food/all/
    - assets/food/burger/
    - assets/food/chicken/
    - assets/food/desserts/
    - assets/food/drink/
    - assets/food/receipe/
    - assets/food/salad/ 
    - assets/food/sandwish/
    - assets/food/seafood/ 
    - assets/food/soup/
    - assets/food/brand_company/
    #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
